config/routes.rb
Rails.application.routes.draw do
  

  mount Shoppe::Engine => "/shoppe"
  
  get 'home/index'
  root 'home#index'

  get "beer/:permalink", to: "beers#show", as: "beer"
  post "beer/:permalink", to: "beers#buy", as: "buy_beer"
  
  get "beers/index" 
  get "beers"  , to: "beers#index" , as: "beers"

  post "beer/:permalink", to: "beers#buy"
  delete "beer/:permalink", to: "beers#remove"
  
  get "basket", to: "orders#show"
  delete "basket", to: "orders#destroy"

  match "checkout", to: "orders#checkout", as: "checkout", via: [:get, :patch]
  match "checkout/pay", to: "orders#payment", as: "checkout_payment", via: [:get, :post]
  match "checkout/confirm", to: "orders#confirmation", as: "checkout_confirmation", via: [:get, :post]
  get "checkout/paypal", to: "orders#paypal"

  resources :users, only: [:new, :create]
  get '/sign_up', to: 'users#new', as: :sign_up

  resources :sessions, only: [:new, :create, :destroy]
  get '/log_in', to: 'sessions#new', as: :log_in
  delete '/log_out', to: 'sessions#destroy', as: :log_out

  

end

app/models/shoppe.rb
module Shoppe
  def self.table_name_prefix
    'shoppe_'
  end
end

app/models/shoppe/user.rb
class Shoppe::User < ActiveRecord::Base
  authenticates_with_sorcery!
  alias_attribute :email_address, :email

  	validates :password, length: { minimum: 3 }, if: -> { new_record? || changes["password"] }
  	validates :password, confirmation: true, if: -> { new_record? || changes["password"] }
  	validates :password_confirmation, presence: true, if: -> { new_record? || changes["password"] }
	  validates :email, uniqueness: true, email_format: { message: 'has invalid format' }
	#validates :first_name, :presence => true
  #  validates :last_name, :presence => true

  def full_name
       "#{first_name} #{last_name}"
    end
  
     def short_name
       "#{first_name} #{last_name[0,1]}"
     end


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  #before_action :require_login

  def current_order
    @current_order ||= begin
      if has_order?
        @current_order
      else
        order = Shoppe::Order.create(:ip_address => request.ip)
        session[:order_id] = order.id
        order
      end
    end
  end

  def has_order?
    !!(
      session[:order_id] &&
      @current_order = Shoppe::Order.includes(:order_items => :ordered_item).find_by_id(session[:order_id])
    )
  end

  helper_method :current_order, :has_order?

  private

  def not_authenticated
    flash[:warning] = 'You have to authenticate to access this page.'
    redirect_to log_in_path
  end
end

app/controllers/beers_controller.rb
class BeersController < ApplicationController
  def index
    @beers =  Shoppe::ProductCategory.find(4).products
    @badges= Hash.new
    current_order.order_items.collect { |x|  @badges[x.ordered_item.permalink.to_sym] = x.quantity}  
    

    #    @beers = Shoppe::Product.root.ordered.includes(:product_categories, :variants)
    #@beers = @beers.group_by(&:product_category)
  end

  def show
    @beers = Shoppe::Product.root.find_by_permalink(params[:permalink])
  end

  def buy
    begin  
      @beer = Shoppe::Product.root.find_by_permalink!(params[:permalink])
      current_order.order_items.add_item(@beer, 1)
    rescue Shoppe::Errors::NotEnoughStock  
        respond_to do |format|
        format.html { 
          redirect_to beers_index_path, :notice => "Lo sentimos pero no tenemos más existencias del producto seleccionado"
        }
        format.json { 
            render json: {error: "Lo sentimos pero no tenemos más existencias del producto seleccionado"} , status: :not_acceptable
          }
      end
    else  
      respond_to do |format|
        format.html { 
          redirect_to beers_index_path, :notice => "Product has been added successfuly!"
        }
        format.json { 
            render json: {total_items: current_order.total_items+1, total_before_tax: current_order.total_before_tax + @beer.price } 
          }
      end 
    end  
  end

  def remove
    begin  
      @beer = Shoppe::Product.root.find_by_permalink!(params[:permalink])
      
      current_order.order_items.each do |item|
        if item.ordered_item.permalink == params[:permalink]
          item.decrease!
        end
      end
    rescue  Exception => e 
        
    else  
      respond_to do |format|
        format.html { 
          redirect_to beers_index_path, :notice => "Product has been added successfuly!"
        }
        format.json { 
            render json: {total_items: current_order.total_items, total_before_tax: current_order.total_before_tax  } 
          }
      end 
    end  
  end


end

app/controllers/home_controller.rb
class HomeController < ApplicationController
	skip_before_action :require_login
  def index
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
	before_filter(only: [:paypal, :payment]) { Shoppe::Paypal.setup_paypal }
	def destroy
	  current_order.destroy
	  session[:order_id] = nil
	  redirect_to root_path, :notice => "Basket emptied successfully."
	end

	def checkout
	  @order = Shoppe::Order.find(current_order.id)
	  if request.patch?
	    if @order.proceed_to_confirm(params[:order].permit(:first_name, :last_name, :billing_address1, :billing_address2, :billing_address3, :billing_address4, :billing_country_id, :billing_postcode, :email_address, :phone_number))
	      redirect_to checkout_payment_path
	    end
	  end
	end



	def confirmation
	  if request.post?
	    current_order.confirm!
	    session[:order_id] = nil
	    redirect_to root_path, :notice => "Order has been placed successfully!"
	  end
	end

	def payment
		if params[:success] == "true" && params[:PayerID].present?
		  @order = Shoppe::Order.find(current_order.id)
		  @order.accept_paypal_payment(params[:paymentId], params[:token], params[:PayerID])
		end
		if request.post?
	    	redirect_to checkout_confirmation_path
	  	end
	end

	def paypal
	  @order = Shoppe::Order.find(current_order.id)
	  url = @order.redirect_to_paypal(checkout_payment_url(success: true), checkout_payment_url(success: false))
	  redirect_to url
	end
	

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
	#skip_before_action :require_login, except: [:destroy]
  def new
  end

  def create
    if login(params[:email], params[:password])
      flash[:success] = 'Welcome back!'
      redirect_back_or_to root_path
      #redirect_to root_path
    else
      flash.now[:warning] = 'E-mail and/or password is incorrect.'
      render 'new'
    end
  end

  def destroy
    logout
    flash[:success] = 'See you!'
    redirect_to log_in_path
  end
end

app/controllers/users_controller.rb
#este controlador mantiene la logica de usuarios customer
class UsersController < ApplicationController
	#skip_before_action :require_login, only: [:new, :create]
	def new
		flash[:notice] = "crear usuario"
		@user = Shoppe::User.new
	end

	def create
		@user = Shoppe::User.new(user_params)
		if @user.save
			login(params[:user][:email], params[:user][:password])
			flash[:success] = 'Tu cuenta ha sido creada. Bienvenido Pirata!'
			redirect_back_or_to beers_path
		else
			render 'new'
		end
	end

	private

	def user_params
		params.require(:user).permit(:email, :password, :password_confirmation, :nickname)
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/beers_helper.rb
module BeersHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/beers/_beer.html.erb
<div class="piecesOfEight-center piecesOfEight  piecesOfEight-space piecesOfEight-black " id= <%= beer.permalink %> >
	<div class="beer-title"> <%= beer.name %> <span class="badge"><%= total.to_i %></span></div>
	<div class="beer-subtitle "> <%= beer.short_description %></div>
	<div class="image-container beer-image-container"  >
		<%= image_tag "beers/beer-1.png", alt:"Card image cap", class:"img-responsive" %>
	</div>
	<div class="">
		<p class="piecesOfEight-black"> 
			<%= number_to_currency beer.price %>
		</p>
		<p>
      <%- if total.to_i > 0%>
        <%= button_tag(class: "btn btn-warning btn-sm piecesOfEight-black btn-remove ", "data-permalink" => beer.permalink , "data-authenticity_token" =>  form_authenticity_token )  do %>
            <i class="fa fa-minus-circle "></i>  
        <% end %>
      <% else %>
      <%= button_tag(class: "btn btn-warning btn-sm piecesOfEight-black btn-remove no-visible-button", "data-permalink" => beer.permalink , "data-authenticity_token" =>  form_authenticity_token )  do %>
            <i class="fa fa-minus-circle "></i>  
        <% end %>
      <% end %>

      <%= button_tag(class: "btn btn-warning btn-sm piecesOfEight-black btn-buy", "data-permalink" => beer.permalink , "data-authenticity_token" =>  form_authenticity_token )  do %>
          <i class="fa fa-plus-circle "></i> 
        <% end %>
			
		</p>

	</div>
</div>

app/views/beers/_footer.html.erb
_footer.html.erb

app/views/beers/_nav_bar.html.erb
<!-- header 1-->
<nav class="navbar navbar-fixed-top navbar-default">
	<div class="container-fluid">
		<!-- Brand and toggle get grouped for better mobile display -->
		<div class="navbar-header">
			<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
				<span class="sr-only">Toggle navigation</span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
			</button>
			<a class="navbar-brand piecesOfEight" href="http://localhost:3000">Jack's Beers </a>
		</div>

		<!-- Collect the nav links, forms, and other content for toggling -->
		<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
			
			<div>
				<ul class="nav navbar-nav piecesOfEight piecesOfEight-space piecesOfEight-xs">
					<li  class=" active">
						<a id="" href="#">Cervezas</a>
					</li>
					<li>
						<a href="#">Jack's packs</a>
					</li>
					<li class="navbar-right">
						<a href="#"><span class="icon fa fa-beer "></span>&nbsp;&nbsp;Comprar</a>
					</li>
					<li  class=" navbar-right">
						<a href="#"><span class="icon fa fa-sign-in"></span>&nbsp;&nbsp;Entrar</a>
					</li>

					<li class="dropdown navbar-right">
			          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Más de Jack <span class="caret"></span></a>
			          <ul class="dropdown-menu">
			            <li><a href="#">Multimedia</a></li>
			            <li><a href="#">Galeria</a></li>
			            <li><a href="#">Noticias</a></li>
			            <li role="separator" class="divider"></li>
			            <li><a href="#">Contacto</a></li>
			          </ul>
			        </li>
					
				</ul>
			</div>

			<div class="collapse navbar-collapse" id="navbar-ex-collapse">

				<ul class="nav navbar-nav navbar-right">
					<li class="dropdown">
			          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Más de Jack <span class="caret"></span></a>
			          <ul class="dropdown-menu">
			            <li><a href="#">Multimedia</a></li>
			            <li><a href="#">Galeria</a></li>
			            <li><a href="#">Noticias</a></li>
			            <li role="separator" class="divider"></li>
			            <li><a href="#">Contacto</a></li>
			          </ul>
			        </li>
					<li class="active">
						<a href="#"><span class="icon fa fa-beer "></span>&nbsp;&nbsp;Comprar</a>
					</li>
					<li>
						<a href="#"><span class="icon fa fa-sign-in"></span>&nbsp;&nbsp;Entrar</a>
					</li>
				</ul>
			</div>
			
		</div><!-- /.navbar-collapse -->
	</div><!-- /.container-fluid -->
</nav>

<!-- header 1-->

app/views/beers/_nav_bar2.html.erb
<nav class="navbar navbar-default nav-bar-no-padding-bottom " role="navigation" >
	<div class="container-fluid">
		<div class="navbar-header hidden-md hidden-lg">
			<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
				<span class="sr-only">Toggle navigation</span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
			</button>
			<a class="navbar-brand piecesOfEight" href="#">Jack's Beers </a>
		</div>

		<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
			
			<div class="hidden-md hidden-lg">
				<ul class="nav navbar-nav piecesOfEight piecesOfEight-space ">
					<li role="presentation" class="active">
						<a id="home-jump"  href="#"  class=>Noticias</a>
					</li>
					<li>
						<a id="services-jump" href="#"> Cervezas</a>
					</li>
					<li>
						<a id="services-jump" href="#">Jack's Packs</a>
					</li>
					
					
					
				</ul>
			</div>

			<div class="collapse navbar-collapse piecesOfEight piecesOfEight-space piecesOfEight-xs piecesOfEight-white" id="navbar-ex-collapse">
				<ul class="nav navbar-nav navbar-right">
					<li class="">
						<%= link_to  basket_path  do %>
						<span class="fa fa-shopping-cart"></span>Carrito
						<% end %>
						
					</li>
					<li>

						<a href="#"><span class=" fa fa-sign-in"></span>&nbsp;&nbsp;Entrar</a>
					</li>
					<li>

						<a href="#"><span class=" fa fa-sign-in"></span>&nbsp;&nbsp;Crear cuenta</a>
					</li>
				</ul>
			</div>
			
		</div>
	</div>
</nav>

app/views/beers/index.html.erb
<section class='content-section '  id="beers-section">
  <div class="container-fluid full-screen-container-fluid  ">
    <!-- <div class="alert alert-danger piecesOfEight  piecesOfEight-space piecesOfEight-black piecesOfEight-xs" role="alert">Recuerdas que los precios son por Six packs </div> -->
    <% if current_order %>
      <div class="alert alert-success piecesOfEight  piecesOfEight-space piecesOfEight-black piecesOfEight-xs" role="alert">
        Tienes <span id="counter"><%=  current_order.total_items %></span> productos en tu compra. Total $ 
        <span id="counter2"><%= current_order.total_before_tax %> </span>
      </div>

      <div class=" notice piecesOfEight  piecesOfEight-space piecesOfEight-black piecesOfEight-xs" style="visibility:hidden;">
       <%=  flash[:notice] %>
     </div>
    
    <% end %>
    <% if  flash[:notice] %>
    <div class="alert alert-warning alert-dismissible" role="alert">
       <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
      <%= flash[:notice] %>
    </div>
    <% end %>
    
    <% @beers.in_groups_of(4, false).each do |group| %>
    <div class='row'>
      <% group.each do |beer| %>
      <div class='col-xs-6   col-sm-4 col-md-3 full-screen-container-fluid '>
        <div class="container-fluid full-screen-container-fluid ">
          <%= render partial: "beer", locals:{beer: beer , total: @badges[beer.permalink.to_sym]}%>
        </div>
      </div>
      <% end %>
    </div>
    <% end %>
  </div>
</section>


<%= render partial: "footer" %>

app/views/home/_about.html.erb
<section class='content-section full-screen-container-fluid-2'  id="about-section">
	<div class="container-fluid full-screen-container-fluid">
		<div class="row  " >
			<h1 class="piecesOfEight piecesOfEight-xbig piecesOfEight-space piecesOfEight-black piecesOfEight-center"> Acerca de Jack's Beers </h1>

			<div class="about-container" id="about-section-row">
				<p>
				 	Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean feugiat lorem elit, vel mattis nibh faucibus non. Ut eget dapibus enim, vitae ullamcorper mi. Aliquam gravida, velit et sodales lacinia, augue sem maximus ipsum, ut convallis dolor nisl id sapien. Quisque quis justo ultricies, tempus magna vel, rutrum mauris. Ut id magna in libero vestibulum suscipit sit amet eget lectus. Fusce ornare ex turpis, blandit gravida ipsum bibendum nec. Nunc blandit elit enim, et pellentesque magna bibendum vitae. Proin nec ullamcorper justo.
				 </p>

				 <p>
				 	Donec finibus tortor sit amet finibus gravida. Nam lacus orci, porta in ante ut, luctus suscipit nibh. Integer sagittis, sem ac porttitor lobortis, mauris neque tristique neque, nec volutpat mauris odio nec elit. Fusce placerat tortor vitae nisi hendrerit efficitur. Morbi a odio lectus. Etiam fringilla ex at diam eleifend, ac interdum mi pharetra. Donec ut ante sed turpis euismod molestie. Quisque dignissim, magna vel congue gravida, nisl odio consequat leo, a imperdiet quam ex eu ligula. Nunc lacus nunc, pretium quis fringilla a, lobortis sit amet quam. Ut convallis, ipsum eget placerat dignissim, tellus nibh interdum ligula, sed finibus augue dolor in ante. Duis eleifend dictum dolor, eu varius leo porta eu. Nulla facilisis leo et nulla blandit pulvinar. Pellentesque luctus consectetur elit in consequat. Aenean nisi arcu, ullamcorper eu erat ut, congue tempor enim. Curabitur eget nisl vehicula, lobortis diam cursus, lobortis eros.
			 </p>
			</div>
		</div>
		<br>
		<br>

		<div class="row" id="features-section-row">
			<div class=" col-xs-12 col-sm-12 col-md-4 " >
	         	<div class="card">
					<div class="card-block">
						<h4 class="card-title"> Titulo </h4>
						<h6 class="card-subtitle text-muted"> subtitulo</h6>
					</div>
					<%= image_tag "pirates-icons-rum.png",class: "img-responsive  centered-image" , alt:"Card image cap" %>
					<div class="card-block">
						<p class="card-text"> alsdkajdklas</p>
						
					</div>
				</div>   
	        </div>
	        <div class=" col-xs-12 col-sm-12 col-md-4 " >
	         	<div class="card">
					<div class="card-block">
						<h4 class="card-title"> Titulo</h4>
						<h6 class="card-subtitle text-muted"> subtitulo</h6>
					</div>
					<%= image_tag "pirates-icons-rum.png",class: "img-responsive  centered-image" , alt:"Card image cap" %>
					<div class="card-block">
						<p class="card-text"> alsdkajdklas</p>
						
					</div>
				</div>   
	        </div>
	        <div class=" col-xs-12 col-sm-12 col-md-4 " >
	         	<div class="card">
					<div class="card-block">
						<h4 class="card-title"> Titulo</h4>
						<h6 class="card-subtitle text-muted"> subtitulo</h6>
					</div>
					<%= image_tag "pirates-icons-rum.png",class: "img-responsive  centered-image" , alt:"Card image cap" %>
					<div class="card-block">
						<p class="card-text"> alsdkajdklas</p>
						
					</div>
				</div>   
	        </div>
			
		</div>
	</div>
</section>

app/views/home/_covertura.html.erb
<section class='content-section full-screen-container-fluid-2'  id="covertura-section">
	<div class="container-fluid full-screen-container-fluid">
		<h1 class="piecesOfEight piecesOfEight-xbig piecesOfEight-space piecesOfEight-black piecesOfEight-center"> Covertura </h1>
		<div class="">
				<%= image_tag "map.png",class: "img-responsive  centered-image", alt:"Card image cap" %>
		</div>
	</div>
</section>

app/views/home/_features.html.erb
<section class='features-section content-section '  id="features-section">
	<div class="container-fluid full-screen-container-fluid" >
		
			
		
		<div class="row ">
			<div class="col-md-1 ">
			</div>
			<div class="col-md-4 ">
				<div class="card card-with-opacity">
				  
				  <%= image_tag "pirates-icons-ship.png", class:  "card-img-top", alt:"Card image cap"%>
				  <div class="card-block">
				    <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
				  </div>
				</div>
			</div>
			<div class="col-md-2 ">
			</div>
			<div class="col-md-4 ">
				<div class="card card-with-opacity">
				  
				  <%= image_tag "pirates-icons-rum.png", class:  "card-img-top", alt:"Card image cap"%>
				  <div class="card-block">
				    <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
				  </div>
				</div>
			</div>
			<div class="col-md-1 ">
			</div>
			
	    </div>

	    <div class="row ">
			
			<div class="col-md-1 ">
			</div>
			<div class="col-md-4 ">
				<div class="card card-with-opacity">
				  
				  <%= image_tag "pirates-icons-ship.png", class:  "card-img-top", alt:"Card image cap"%>
				  <div class="card-block">
				    <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
				  </div>
				</div>
			</div>
			<div class="col-md-2 ">
			</div>
			<div class="col-md-4 ">
				<div class="card card-with-opacity">
				  
				  <%= image_tag "pirates-icons-ship.png", class:  "card-img-top", alt:"Card image cap"%>
				  <div class="card-block">
				    <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
				  </div>
				</div>
			</div>
			<div class="col-md-1 ">
			</div>
			
			
	    </div>

	    
	    

	</div>
</section>

app/views/home/_separator.html.erb
<section class="section-separator  section-separator-1  messages-color-1" id="<%= id %>"> 
	<div class="container-fluid">
		<div class="">
			
  			<h1 class=" message piecesOfEight piecesOfEight-center piecesOfEight-space piecesOfEight-golden piecesOfEight-big" ><%= message %></h1>
  			<h2 class="  piecesOfEight piecesOfEight-center piecesOfEight-space piecesOfEight-white piecesOfEight-md "><%= message2 %></h2>
		</div>
		
		
	</div>
</section>

app/views/home/index.html.erb
<%= render partial: "home" %>
<%= render partial: "separator" , locals:{message:"Jack's Beers, que la cerveza vaya a ti!!! ",message2:"Somo el único servicio de cerveza a domicilio",id:""}%>
<%= render partial: "beers" %>
<%= render partial: "separator" , locals:{message:"Jack's Beers, que la cerveza vaya a ti!!! ",message2:"Somo el único servicio de cerveza a domicilio",id:""}%>
<%= render partial: "packs" %>
<%= render partial: "separator" , locals:{message:"Jack's Beers, que la cerveza vaya a ti!!! ",message2:"Somo el único servicio de cerveza a domicilio",id:""}%>
<%= render partial: "about" %>
<%= render partial: "covertura" %>

<%= render partial: "footer" %>

<div class="floating-buttons piecesOfEight piecesOfEight-xxs piecesOfEight-space piecesOfEight-black piecesOfEight-center  hidden-sm hidden-xs ">
		<!--
		<div class="floating-buttons-item">
			<button type="button" class="btn btn-primary"><i class="fa fa-beer fa-2x"></i>Comprar</button>
		</div>

	-->
	<% if current_user.nil? %>
		<div class="floating-buttons-item piecesOfEight-left">
			<button type="button" class="btn btn-success"><i class="fa fa-sign-in fa-2x"></i>Entrar</button>
		</div>
		<div class="floating-buttons-item">

			<%= link_to  new_user_path , class:"btn btn-primary piecesOfEight-left" do %>

			<i class="fa fa-user-plus fa-2x"></i> Crear cuenta
			<% end %>
		</div>
		
	<% else %>
		<div class="floating-buttons-item piecesOfEight-left">
			<div class="btn-group">
			  <button type="button" class="btn btn-success dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
			    <%= current_user.nickname %> <span class="caret"></span>
			  </button>
			  <ul class="dropdown-menu">
			    <li><a href="#">Salir</a></li>
			  </ul>
			</div>
		</div>
	<% end %>
	
</div>

app/views/orders/checkout.html.erb
<h2>Checkout</h2>
<%= render 'items', :order => @order %>

<%= form_for @order, :url => checkout_path do |f| %>
    <% if @order.errors.full_messages.any? %>
        <% @order.errors.full_messages.each do |error_message| %>
        <%= error_message if @order.errors.full_messages.first == error_message %> <br />
        <% end %>
    <% end %>
  <dl>
    <dt><%= f.label :first_name, 'Name' %></dt>
    <dd><%= f.text_field :first_name %> <%= f.text_field :last_name %></dd>

    <dt><%= f.label :billing_address1, 'Address' %></dt>
    <dd><%= f.text_field :billing_address1 %></dd>
    <dd><%= f.text_field :billing_address2 %></dd>
    <dd><%= f.text_field :billing_address3 %></dd>
    <dd><%= f.text_field :billing_address4 %></dd>
    <dt><%= f.label :billing_postcode, 'Post code' %></dt>
    <dd><%= f.text_field :billing_postcode %></dd>
    <dd><%= f.collection_select :billing_country_id, Shoppe::Country.ordered, :id, :name, :include_blank => true %></dd>

    <dt><%= f.label :email_address %></dt>
    <dd><%= f.text_field :email_address %></dd>

    <dt><%= f.label :phone_number %></dt>
    <dd><%= f.text_field :phone_number %></dd>

    <dd><%= f.submit 'Continue' %></dd>
  </dl>
<% end %>

app/views/orders/confirmation.html.erb
<h2>Place your order</h2>
<%= render 'items', :order => current_order %>
<%= button_to "Place order" %>

app/views/orders/payment.html.erb
<h2>Make your payment</h2>

<% if params[:success] == "true" && params[:PayerID].present? %>

  <p>Payment will be processed by PayPal</p>
  <%= link_to "Continue", checkout_confirmation_path %>

<% else %>

  <%= form_tag nil, class: "stripeForm" do %>
    <%= hidden_field_tag "stripe_token", nil, "data-stripe" => "token" %>
    <dl>
      <dt><%= label_tag 'card_number' %></dt>
      <dd><%= text_field_tag 'card_number', nil, name: nil, "data-stripe" => "number" %></dd>
      <dt><%= label_tag 'expiry_month' %></dt>
      <dd><%= text_field_tag 'expiry_month', nil, name: nil, "data-stripe" => "exp_month" %></dd>
      <dt><%= label_tag 'expiry_year' %></dt>
      <dd><%= text_field_tag 'expiry_year', nil, name: nil, "data-stripe" => "exp_year" %></dd>
      <dt><%= label_tag 'security_code' %></dt>
      <dd><%= text_field_tag 'security_code', nil, name: nil, "data-stripe" => "cvc" %></dd>
      <dd><%= submit_tag "Continue" %></dd>
    </dl>
  <% end %>

  <hr>

  <%= link_to "Pay with PayPal", checkout_paypal_path %>

<% end %>

app/views/orders/show.html.erb
<% if current_order %>
      <div class="alert alert-success piecesOfEight  piecesOfEight-space piecesOfEight-black piecesOfEight-xs" role="alert">
        Tienes <%= pluralize current_order.total_items, 'productos'%> en tu compra. Total: <%= number_to_currency current_order.total_before_tax %>. 
        <%= flash[:notice] %>
      </div>
    <% end %>
<h2>Your basket</h2>
<%= render 'items', :order => current_order %>
<p><%= button_to 'Empty basket', basket_path, :method => :delete %></p>
<%= link_to "Checkout", checkout_path %>

app/views/users/_nav_bar2.html.erb
_nav_bar2.html.erb